version: "{branch} {build}"
install:
  - ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
  - ps: scoop install gradle
build:
  verbosity: detailed

build_script:
  - gradle assemble --info --no-daemon

test_script:
  - gradle check --info --no-daemon

branches:
  only:
    - master    

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix: 
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
 
matrix:
  fast_finish: true

artifacts:
- path: ./build/libs
  name: octane-gocd-plugin.$(appveyor_build_version).jar
  type: zip
