# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
  AlmOctaneConnections: ['Octane']

jobs:
- job: AlmOctanePipelineStart
  condition: always()

- job: Moshe
  steps:
  - script: echo Hello, Moshe!
    displayName: 'Run a one-line script'
  dependsOn:
  - AlmOctanePipelineStart


- job: Avigail
  steps:
  - script: echo Hello, Avigail!
    displayName: 'Run a one-line script'
  dependsOn:
  - AlmOctanePipelineStart

- job: AlmOctanePipelineEnd
  condition: always()
  dependsOn:
  - AlmOctanePipelineStart
  - Moshe
  - Avigail
